config/routes.rb
Micex::Application.routes.draw do  

  resources :shares do
    get :update_data, :on => :member
    get :update_monthly_values, :on => :member
    resources :trades
    resources :charts do
      get :buysell, :on => :collection
      get :ohlc, :on => :collection
      get :update_charts, :on => :collection
    end
  end
  
  root :to => redirect("/shares/gazp")

end

app/models/share.rb
class Share
  include MicexApi
  include MicexCsvApi
  include Mongoid::Document
  field :ticker, :type => String
  field :board, :type => String
  key :ticker
  has_many :candles
  has_many :trades
  has_many :trade_stats
  has_many :values
  has_many :monthly_values
  
  def get_trades_by_api
    self.get_trades
  end
  
  def get_values_for_period(date1=Time.now, date2=Time.now)
    # tradesScope = Trade.for_period(date1,date2).for_share(self.id).order_by(['tradetime', 'asc'])
    valuesScope = Value.for_dates(date1, date2).order(['date', 'asc'])
    values = valuesScope.to_a.sum &:values
    # tradesScope = 
    #   Trade.connection.find(
    #     {:tradetime => {"$gt" => date1.beginning_of_day.utc, "$lt" => date2.end_of_day.utc}, :share_id => self.id}, 
    #     {:fields => ['price','tradetime','buysell','quantity'], :hint => {tradetime: 1}}
    #   )
    # values = [Value.get_last_value(self, date1)]
    # tradesScope.each do |trade|
    #   values << values.last + trade.net_value
    # end
    return values
  end
  
  def get_prices_for_period(date1=Time.now, date2=Time.now)
    tradesScope = 
      Trade.connection.find(
        {:tradetime => {"$gt" => date1.beginning_of_day.utc, "$lt" => date2.end_of_day.utc}, :share_id => self.id}, 
        {:fields => ['price'], :hint => {tradetime: 1}}
      )
    
    return tradesScope.map{|trade| trade['price']}
  end
end

app/controllers/shares_controller.rb
class SharesController < InheritedResources::Base
  actions :show
  respond_to :js, :only => :update_data
  custom_actions :member => :update_data
  # before_filter :get_share, :only => [:show, :update_data]
  before_filter :get_values, :only => :show
  
  def update_data
    Value.daily_values_for(resource) if resource.get_trades_by_api
  end
  
  def update_monthly_values
    result = MonthlySummary.generate_for(resource, Date.today.month, Date.today.year)
    message = result ? "Updates" : "Error"
    redirect_to resource, :flash => {:notice => message}
  end
  
  private

  def get_values
    @values = resource.values.order([:date,:desc])
  end
end

app/helpers/shares_helper.rb
module SharesHelper
  def chart_from_micex_for(share, date1, date2, period)
    micex_url = "http://www.micex.ru/cs_compat?"
    query_params = {
      :secid => share.ticker,
      :timeline => date1.strftime('%Y.%m.%d')+'-'+date2.strftime('%Y.%m.%d'),
      :template => 'micextest',
      :trade_engine => 'stock',
      :market => 'shares',
      :linetype => 'candles',
      :board_group_id => 6,
      :interval => {'week' => 60, 'day' => 10, 'month' => 24, 'quarter' => 24, 'year' => 7}[period],
      :period => {'week' => '-7d', 'day' => '-1d', 'month' => '-1M', 'quarter' => '-3M', 'year' => '-1y'}[period],
      :lang => 'ru'
    }
    
    image_tag micex_url + query_params.to_query, :width => 700
  end
end

app/views/shares/_form.html.haml
= form_for @share do |f|
  -if @share.errors.any?
    #error_explanation
      %h2= "#{pluralize(@share.errors.count, "error")} prohibited this share from being saved:"
      %ul
        - @share.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :ticker
    = f.text_field :ticker
  .field
    = f.label :board
    = f.text_field :board
  .actions
    = f.submit 'Save'

app/views/shares/edit.html.haml
%h1 Editing share

= render 'form'

= link_to 'Show', @share
\|
= link_to 'Back', shares_path

app/views/shares/index.html.haml
%h1 Listing shares

%table
  %tr
    %th Ticker
    %th
    %th
    %th

  - @shares.each do |share|
    %tr
      %td= share.ticker
      %td= link_to 'Show', share
      %td= link_to 'Edit', edit_share_path(share)
      %td= link_to 'Destroy', share, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Share', new_share_path

app/views/shares/new.html.haml
%h1 New share

= render 'form'

= link_to 'Back', shares_path

app/views/shares/show.html.haml
%p#notice= notice
= content_for :title do
  = @share.ticker
    
.charts.clearfix
  .float-left
    %ul
      %li= link_to "<button>Update data from Micex</button>".html_safe, update_data_share_path(@share), :remote => true, :id => "update-data"
      %li= link_to "<button>Update monthly data</button>".html_safe, update_monthly_values_share_path(@share)
      
      %hr
      %li= link_to "Buy/sell current month", buysell_share_charts_path(@share, :from => Date.today.beginning_of_month, :to => Date.today.end_of_month)
      %li= link_to "Buy/sell cumulative", buysell_share_charts_path(@share, :from => @share.values.first.date.beginning_of_month, :to => Date.today.end_of_month)
      - for value in @values
        %li= link_to "Buy/sell graph for #{value.date.to_s}", buysell_share_charts_path(@share, :from => value.date.to_s, :to => value.date.to_s)
      
  .float-left
    .chart-periods-links
      = link_to "year", "#", :class => '', :id => 'show-year-chart', :data_period => 'year-chart'
      |
      = link_to "quarter", "#", :class => '', :id => 'show-quarter-chart', :data_period => 'quarter-chart'
      |
      = link_to "month", "#", :class => '', :id => 'show-month-chart', :data_period => 'month-chart'
      |
      = link_to "week", "#", :class => '', :id => 'show-week-chart', :data_period => 'week-chart'
      |
      = link_to "day", "#", :id => 'show-day-chart', :data_period => 'day-chart', :class => 'active'
    .micex-charts
      .year-chart{:style => 'display:none;'}= chart_from_micex_for(@share, 1.year.ago, 1.day.from_now, 'year')
      .quarter-chart{:style => 'display:none;'}= chart_from_micex_for(@share, 3.month.ago, 1.day.from_now, 'quarter')
      .month-chart{:style=>'display:none;'}= chart_from_micex_for(@share, 31.days.ago, 1.day.from_now, 'month')
      .week-chart{:style=>'display:none;'}= chart_from_micex_for(@share, 7.days.ago, 1.day.from_now, 'week')
      .day-chart= chart_from_micex_for(@share, 7.day.ago, 1.day.from_now, 'day')


%p
  %b Ticker:
  = @share.ticker

= link_to 'Edit', edit_share_path(@share)
|
= link_to 'Back', shares_path
|
= link_to 'show trades', share_trades_path(@share)

app/views/shares/update_data.js.erb
window.location="<%= buysell_share_charts_path(@share) %>"
// $.unblockUI({});