config/routes.rb
Micex::Application.routes.draw do  

  resources :shares do
    get :update_data, :on => :member
    get :update_monthly_values, :on => :member
    resources :trades
    resources :charts do
      get :buysell, :on => :collection
      get :ohlc, :on => :collection
      get :update_charts, :on => :collection
    end
  end
  
  root :to => redirect("/shares/gazp")

end

app/models/trade.rb
class Trade
  include MicexApi
  include Mongoid::Document
  include Mongoid::Timestamps

  FIELDS = ["TRADENO","TRADETIME","BOARDID","SECID","PRICE","QUANTITY","BUYSELL"]

  field :tradeno, :type => Integer
  field :tradetime, :type => Time
  field :boardid, :type => String
  field :secid, :type => String
  field :price, :type => Float
  field :quantity, :type => Integer
  field :buysell, :type => String

  index :tradeno
  index :tradetime

  belongs_to :share
  
  scope :for_share, ->(share_id) { where(:share_id => share_id) }
  scope :for_date, ->(date) { where(:tradetime.gt => date.beginning_of_day, :tradetime.lt => date.end_of_day) }
  scope :for_period, ->(from,to) {where(:tradetime.gt => from.beginning_of_day, :tradetime.lt => to.end_of_day)}
  scope :for_hour, ->(time) { where(:tradetime.gt => time, :tradetime.lt => time + 1.hour)}
  
  def buysell_sign
    buy? ? 1 : -1
  end
  
  def buy?
    buysell == "B"
  end
  
  def net_value
    buysell_sign * (price * quantity)
  end
  
  class << self
    def count_stats_for(share, date, kind)
      date ||= Date.today
      kind ||= TradeStat::KINDS[:buysell]
      case kind
      when TradeStat::KINDS[:buysell]
        buysell_stats_for(share, date)
      when TradeStat::KINDS[:firstlast]
        firstlast_stats_for(share, date)
      end
    end
        
    def firstlast_stats_for(share, date)
      tradesScope = self.where(:share_id => share.id).for_date(date).order_by([:tradeno, :asc]).only(:tradetime, :buysell, :price, :quantity).all
      return nil unless tradesScope.any?
      start_value = tradesScope.first.net_value
      end_value = 0
      tradesScope.all.group_by{|trade| trade.tradetime.hour}.each do |hour, trades|
        trades.each do |trade|
          end_value += trade.net_value.round
        end
      end
      return [start_value, end_value]
    end
    
    def get_last_value(share, date)
      TradeStat.collection.find(
        {:share_id => share.id, :date => {"$lt" => date.utc}, :kind => TradeStat::KINDS[:firstlast]}, 
        {:fields => 'stat_data', :sort => ['date','desc']}
      ).sum{|ts| ts['stat_data'][1]}
    rescue 0
    end
    
    def prev_day_for(date = Date.today)
      prev_day = date.monday? ? date - 3.days : date.yesterday
    end
    
    def connection
      @connection ||= Mongoid::Config.database['trades']
    end
  end
end

app/controllers/trades_controller.rb
require 'will_paginate/array'
class TradesController < InheritedResources::Base
  belongs_to :share
  
  def index
    unless params[:date]
      redirect_to share_trades_path(parent, :date => Date.today)
    end
    @trades = collection
  end
  
  def new
    @trade = parent.trades.build(:secid => parent.ticker)
  end
  
  protected
  def collection
    @date ||= params[:date] ? Date.parse(params[:date]) : Date.today 
    @trades ||= end_of_association_chain.for_date(@date).order_by([:tradeno, :asc]).paginate(:page => params[:page], :per_page => 100)
  end
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/views/trades/_form.html.haml
= form_for @trade, :url => share_trades_path(parent) do |f|
  -if @trade.errors.any?
    #error_explanation
      %h2= "#{pluralize(@trade.errors.count, "error")} prohibited this trade from being saved:"
      %ul
        - @trade.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :tradeno
    = f.number_field :tradeno
  .field
    = f.label :tradetime
    = f.datetime_select :tradetime
  .field
    = f.label :boardid
    = f.text_field :boardid
  .field
    = f.label :secid
    = f.text_field :secid
  .field
    = f.label :price
    = f.text_field :price
  .field
    = f.label :quantity
    = f.number_field :quantity
  .field
    = f.label :value
    = f.text_field :value
  .field
    = f.label :period
    = f.text_field :period
  .field
    = f.label :tradetime_grp
    = f.number_field :tradetime_grp
  .field
    = f.label :systime
    = f.datetime_select :systime
  .field
    = f.label :buysell
    = f.text_field :buysell
  .field
    = f.label :decimals
    = f.number_field :decimals
  .actions
    = f.submit 'save'

app/views/trades/edit.html.haml
%h1 Editing trade

= render 'form'

= link_to 'Show', @trade
\|
= link_to 'Back', share_trades_path(parent)

app/views/trades/index.html.haml
= will_paginate @trades
%h1 Listing trades

%table
  %tr
    %th Tradeno
    %th Tradetime
    %th Boardid
    %th Secid
    %th Price
    %th Quantity
    %th Buysell
    %th
    %th
    %th

  - @trades.each do |trade|
    %tr
      %td= trade.tradeno
      %td= trade.tradetime.strftime("%H-%M %m/%d/%Y")
      %td= trade.boardid
      %td= trade.secid
      %td= trade.price
      %td= trade.quantity
      %td= trade.buysell
      %td= link_to 'Show', share_trade_path(parent, trade)
      %td= link_to 'Edit', edit_share_trade_path(parent,trade)
      %td= link_to 'Destroy', share_trade_path(parent,trade), :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Trade', new_share_trade_path(parent)
|
= link_to 'Shares', shares_path

app/views/trades/new.html.haml
%h1 New trade

= render 'form'

= link_to 'Back', share_trades_path(parent)

app/views/trades/show.html.haml
%p#notice= notice

%p
  %b Tradeno:
  = @trade.TRADENO
%p
  %b Tradetime:
  = @trade.TRADETIME
%p
  %b Boardid:
  = @trade.BOARDID
%p
  %b Secid:
  = @trade.SECID
%p
  %b Price:
  = @trade.PRICE
%p
  %b Quantity:
  = @trade.QUANTITY
%p
  %b Value:
  = @trade.VALUE
%p
  %b Period:
  = @trade.PERIOD
%p
  %b Tradetime grp:
  = @trade.TRADETIME_GRP
%p
  %b Systime:
  = @trade.SYSTIME
%p
  %b Buysell:
  = @trade.BUYSELL
%p
  %b Decimals:
  = @trade.DECIMALS

= link_to 'Edit', edit_trade_path(@trade)
\|
= link_to 'Back', trades_path